apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
- https://github.com/jasonblanchard/di-graphiql/deploy/k8s/production?ref=261dfa2b6c77265a2122b3f0dbe97bcd29a3393c # {"$openapi":"base"}
images:
- name: jasonblanchard/di-graphiql
  newTag: "261dfa2b6c77265a2122b3f0dbe97bcd29a3393c" # {"$openapi":"version"}
commonAnnotations:
  version: "261dfa2b6c77265a2122b3f0dbe97bcd29a3393c" # {"$openapi":"version"}
