apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authn/production
  - public-web/production
  # - velocity/production
  - workspace-web/production
  - notebook/production
