apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
- https://github.com/jasonblanchard/di-notebook/deploy/k8s/production?ref=e6241dc09346b7833b444e23e2c1f09aed5d61f4 # {"$openapi":"base"}
images:
- name: jasonblanchard/di-notebook
  newTag: "e6241dc09346b7833b444e23e2c1f09aed5d61f4" # {"$openapi":"version"}
commonAnnotations:
  version: "e6241dc09346b7833b444e23e2c1f09aed5d61f4" # {"$openapi":"version"}
