apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
- https://github.com/jasonblanchard/di-notebook/deploy/k8s/production?ref=f9c7f9155da6a4555430b8ccf6b1c20093d24abf # {"$openapi":"base"}
images:
- name: jasonblanchard/di-notebook
  newTag: "f9c7f9155da6a4555430b8ccf6b1c20093d24abf" # {"$openapi":"version"}
commonAnnotations:
  version: "f9c7f9155da6a4555430b8ccf6b1c20093d24abf" # {"$openapi":"version"}
