apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
- https://github.com/jasonblanchard/di-notebook/deploy/k8s/production?ref=11daeb65e72d2fe9213c4fde2f46ebdaaa840d71 # {"$openapi":"base"}
images:
- name: jasonblanchard/di-notebook
  newTag: "11daeb65e72d2fe9213c4fde2f46ebdaaa840d71" # {"$openapi":"version"}
commonAnnotations:
  version: "11daeb65e72d2fe9213c4fde2f46ebdaaa840d71" # {"$openapi":"version"}
