apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
- https://github.com/jasonblanchard/di-notebook/deploy/k8s/production?ref=887f6f812de9a2bbb3f57148b3ab74a86efb198e # {"$openapi":"base"}
images:
- name: jasonblanchard/di-notebook
  newTag: "887f6f812de9a2bbb3f57148b3ab74a86efb198e" # {"$openapi":"version"}
commonAnnotations:
  version: "887f6f812de9a2bbb3f57148b3ab74a86efb198e" # {"$openapi":"version"}
