apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
  - https://github.com/jasonblanchard/di-notebook/deploy/k8s/production?ref=2a2d91051bf2b1a02ed5df7dcf3e6f2d0e6b1e97 # {"$openapi":"base"}
images:
  - name: jasonblanchard/di-notebook
    newTag: "2a2d91051bf2b1a02ed5df7dcf3e6f2d0e6b1e97" # {"$openapi":"version"}
commonAnnotations:
  version: "2a2d91051bf2b1a02ed5df7dcf3e6f2d0e6b1e97" # {"$openapi":"version"}
