apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
  - https://github.com/jasonblanchard/di-notebook/deploy/k8s/production?ref=326c31e4b2f6751a92b8b581715081f4da5c7094 # {"$openapi":"base"}
images:
  - name: jasonblanchard/di-notebook
    newTag: "326c31e4b2f6751a92b8b581715081f4da5c7094" # {"$openapi":"version"}
commonAnnotations:
  version: "326c31e4b2f6751a92b8b581715081f4da5c7094" # {"$openapi":"version"}
