apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
- https://github.com/jasonblanchard/di-notebook/deploy/k8s/production?ref=2837d12635281267410eb0388b7bb37483f0cd7a # {"$openapi":"base"}
images:
- name: jasonblanchard/di-notebook
  newTag: "2837d12635281267410eb0388b7bb37483f0cd7a" # {"$openapi":"version"}
commonAnnotations:
  version: "2837d12635281267410eb0388b7bb37483f0cd7a" # {"$openapi":"version"}
