apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
- https://github.com/jasonblanchard/di-notebook/deploy/k8s/production?ref=b287491da4a7e99fa0190a81b0874afae8610a96 # {"$openapi":"base"}
images:
- name: jasonblanchard/di-notebook
  newTag: "b287491da4a7e99fa0190a81b0874afae8610a96" # {"$openapi":"version"}
commonAnnotations:
  version: "b287491da4a7e99fa0190a81b0874afae8610a96" # {"$openapi":"version"}
