apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
- https://github.com/jasonblanchard/di-notebook/deploy/k8s/production?ref=da458178d98d21132985b07ab6a685f49dca868f # {"$openapi":"base"}
images:
- name: jasonblanchard/di-notebook
  newTag: "da458178d98d21132985b07ab6a685f49dca868f" # {"$openapi":"version"}
commonAnnotations:
  version: "da458178d98d21132985b07ab6a685f49dca868f" # {"$openapi":"version"}
