apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
- https://github.com/jasonblanchard/di-notebook/deploy/k8s/production?ref=8c2c932e8efaf7e9a99c85fbe73ab9093b730a02 # {"$openapi":"base"}
images:
- name: jasonblanchard/di-notebook
  newTag: "8c2c932e8efaf7e9a99c85fbe73ab9093b730a02" # {"$openapi":"version"}
commonAnnotations:
  version: "8c2c932e8efaf7e9a99c85fbe73ab9093b730a02" # {"$openapi":"version"}
