apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
- https://github.com/jasonblanchard/di-notebook/deploy/k8s/production?ref=fc78863a047af374ee9a249c9e143d81889d5a15 # {"$openapi":"base"}
images:
- name: jasonblanchard/di-notebook
  newTag: "fc78863a047af374ee9a249c9e143d81889d5a15" # {"$openapi":"version"}
commonAnnotations:
  version: "fc78863a047af374ee9a249c9e143d81889d5a15" # {"$openapi":"version"}
