apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
  - https://github.com/jasonblanchard/di-notebook/deploy/k8s/production?ref=ff824bd8718fc306a9a61d48db4a6a2121f60b69 # {"$openapi":"base"}
images:
  - name: jasonblanchard/di-notebook
    newTag: "ff824bd8718fc306a9a61d48db4a6a2121f60b69" # {"$openapi":"version"}
commonAnnotations:
  version: "ff824bd8718fc306a9a61d48db4a6a2121f60b69" # {"$openapi":"version"}
