apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
- https://github.com/jasonblanchard/di-notebook/deploy/k8s/production?ref=33ec819ee213e81788871f28e05bc43be127db73 # {"$openapi":"base"}
images:
- name: jasonblanchard/di-notebook
  newTag: "33ec819ee213e81788871f28e05bc43be127db73" # {"$openapi":"version"}
commonAnnotations:
  version: "33ec819ee213e81788871f28e05bc43be127db73" # {"$openapi":"version"}
