apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
- https://github.com/jasonblanchard/di-notebook/deploy/k8s/production?ref=898637370e80c0b48be78397d7fbd0eebdd993dd # {"$openapi":"base"}
images:
- name: jasonblanchard/di-notebook
  newTag: "898637370e80c0b48be78397d7fbd0eebdd993dd" # {"$openapi":"version"}
commonAnnotations:
  version: "898637370e80c0b48be78397d7fbd0eebdd993dd" # {"$openapi":"version"}
