apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
- https://github.com/jasonblanchard/di-notebook/deploy/k8s/production?ref=9bc08559d57c428c68c3a4810fea92ee447d7b56 # {"$openapi":"base"}
images:
- name: jasonblanchard/di-notebook
  newTag: "9bc08559d57c428c68c3a4810fea92ee447d7b56" # {"$openapi":"version"}
commonAnnotations:
  version: "9bc08559d57c428c68c3a4810fea92ee447d7b56" # {"$openapi":"version"}
