apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
- https://github.com/jasonblanchard/di-notebook/deploy/k8s/production?ref=b3f6a5c35d15748c725a9ed78337355eaf2e70a0 # {"$openapi":"base"}
images:
- name: jasonblanchard/di-notebook
  newTag: "b3f6a5c35d15748c725a9ed78337355eaf2e70a0" # {"$openapi":"version"}
commonAnnotations:
  version: "b3f6a5c35d15748c725a9ed78337355eaf2e70a0" # {"$openapi":"version"}
