apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
- https://github.com/jasonblanchard/di-notebook/deploy/k8s/production?ref=a038073d92809b919b40222c14b91bcd2fba8ecc # {"$openapi":"base"}
images:
- name: jasonblanchard/di-notebook
  newTag: "a038073d92809b919b40222c14b91bcd2fba8ecc" # {"$openapi":"version"}
commonAnnotations:
  version: "a038073d92809b919b40222c14b91bcd2fba8ecc" # {"$openapi":"version"}
