apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
- https://github.com/jasonblanchard/di-notebook/deploy/k8s/production?ref=8842deec510a13006801bf7c92cc7506bb71472d # {"$openapi":"base"}
images:
- name: jasonblanchard/di-notebook
  newTag: "8842deec510a13006801bf7c92cc7506bb71472d" # {"$openapi":"version"}
commonAnnotations:
  version: "8842deec510a13006801bf7c92cc7506bb71472d" # {"$openapi":"version"}
