apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
- https://github.com/jasonblanchard/di-notebook/deploy/k8s/production?ref=cc200e07bd7951d2ec624f356b411d5ab6385d3d # {"$openapi":"base"}
images:
- name: jasonblanchard/di-notebook
  newTag: "cc200e07bd7951d2ec624f356b411d5ab6385d3d" # {"$openapi":"version"}
commonAnnotations:
  version: "cc200e07bd7951d2ec624f356b411d5ab6385d3d" # {"$openapi":"version"}
