apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
- https://github.com/jasonblanchard/di-notebook/deploy/k8s/production?ref=4dee2cc9b62951bdab0f6333395ab3f89b81802b # {"$openapi":"base"}
images:
- name: jasonblanchard/di-notebook
  newTag: "4dee2cc9b62951bdab0f6333395ab3f89b81802b" # {"$openapi":"version"}
commonAnnotations:
  version: "4dee2cc9b62951bdab0f6333395ab3f89b81802b" # {"$openapi":"version"}
