apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
- https://github.com/jasonblanchard/di-notebook/deploy/k8s/production?ref=36e2d6aae9e9e6138e4b28aed41ecaa5160559a8 # {"$openapi":"base"}
images:
- name: jasonblanchard/di-notebook
  newTag: "36e2d6aae9e9e6138e4b28aed41ecaa5160559a8" # {"$openapi":"version"}
commonAnnotations:
  version: "36e2d6aae9e9e6138e4b28aed41ecaa5160559a8" # {"$openapi":"version"}
