apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
- https://github.com/jasonblanchard/di-notebook/deploy/k8s/production?ref=900238cee5bcaf4728f15785e89c67290ae07b53 # {"$openapi":"base"}
images:
- name: jasonblanchard/di-notebook
  newTag: "900238cee5bcaf4728f15785e89c67290ae07b53" # {"$openapi":"version"}
commonAnnotations:
  version: "900238cee5bcaf4728f15785e89c67290ae07b53" # {"$openapi":"version"}
