apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
- https://github.com/jasonblanchard/di-notebook/deploy/k8s/production?ref=79dda822f53b27c34603ad1b7fc55ad31e011410 # {"$openapi":"base"}
images:
- name: jasonblanchard/di-notebook
  newTag: "79dda822f53b27c34603ad1b7fc55ad31e011410" # {"$openapi":"version"}
commonAnnotations:
  version: "79dda822f53b27c34603ad1b7fc55ad31e011410" # {"$openapi":"version"}
