apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
- https://github.com/jasonblanchard/di-notebook/deploy/k8s/production?ref=306ee8dd6b7eb4cf16cff244b698dd7e42113631 # {"$openapi":"base"}
images:
- name: jasonblanchard/di-notebook
  newTag: "306ee8dd6b7eb4cf16cff244b698dd7e42113631" # {"$openapi":"version"}
commonAnnotations:
  version: "306ee8dd6b7eb4cf16cff244b698dd7e42113631" # {"$openapi":"version"}
