apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
- https://github.com/jasonblanchard/di-notebook/deploy/k8s/production?ref=cd2feafd73b10d5723fca9d55df74cdaa7b275ab # {"$openapi":"base"}
images:
- name: jasonblanchard/di-notebook
  newTag: "cd2feafd73b10d5723fca9d55df74cdaa7b275ab" # {"$openapi":"version"}
commonAnnotations:
  version: "cd2feafd73b10d5723fca9d55df74cdaa7b275ab" # {"$openapi":"version"}
