apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
- https://github.com/jasonblanchard/di-notebook/deploy/k8s/production?ref=21e79bfa9a12dea3242de0408eb6b8d391531e78 # {"$openapi":"base"}
images:
- name: jasonblanchard/di-notebook
  newTag: "21e79bfa9a12dea3242de0408eb6b8d391531e78" # {"$openapi":"version"}
commonAnnotations:
  version: "21e79bfa9a12dea3242de0408eb6b8d391531e78" # {"$openapi":"version"}
