apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
- https://github.com/jasonblanchard/di-notebook/deploy/k8s/production?ref=2231659b50c1ef36347bbccc5eb61cace23b6d8c # {"$openapi":"base"}
images:
- name: jasonblanchard/di-notebook
  newTag: "2231659b50c1ef36347bbccc5eb61cace23b6d8c" # {"$openapi":"version"}
commonAnnotations:
  version: "2231659b50c1ef36347bbccc5eb61cace23b6d8c" # {"$openapi":"version"}
