apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
- https://github.com/jasonblanchard/di-notebook/deploy/k8s/production?ref=02daab1130d09f74cd80b504bd64b327e3dcf80d # {"$openapi":"base"}
images:
- name: jasonblanchard/di-notebook
  newTag: "02daab1130d09f74cd80b504bd64b327e3dcf80d" # {"$openapi":"version"}
commonAnnotations:
  version: "02daab1130d09f74cd80b504bd64b327e3dcf80d" # {"$openapi":"version"}
