apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
- https://github.com/jasonblanchard/di-notebook/deploy/k8s/production?ref=7dcb30e6dac1a084d875a7b8ee9a16b837015ba5 # {"$openapi":"base"}
images:
- name: jasonblanchard/di-notebook
  newTag: "7dcb30e6dac1a084d875a7b8ee9a16b837015ba5" # {"$openapi":"version"}
commonAnnotations:
  version: "7dcb30e6dac1a084d875a7b8ee9a16b837015ba5" # {"$openapi":"version"}
