apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
  - https://github.com/jasonblanchard/di-notebook/deploy/k8s/production?ref=e41902babfdf42b93d3036483b758070826b5bb9 # {"$openapi":"base"}
images:
  - name: jasonblanchard/di-notebook
    newTag: "e41902babfdf42b93d3036483b758070826b5bb9" # {"$openapi":"version"}
commonAnnotations:
  version: "e41902babfdf42b93d3036483b758070826b5bb9" # {"$openapi":"version"}
