apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
- https://github.com/jasonblanchard/di-notebook/deploy/k8s/production?ref=5699a798a2578987e4d2fc8e072e6ef947e29faf # {"$openapi":"base"}
images:
- name: jasonblanchard/di-notebook
  newTag: "5699a798a2578987e4d2fc8e072e6ef947e29faf" # {"$openapi":"version"}
commonAnnotations:
  version: "5699a798a2578987e4d2fc8e072e6ef947e29faf" # {"$openapi":"version"}
