apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
- https://github.com/jasonblanchard/di-notebook/deploy/k8s/production?ref=b69a069fc18c2a8a80c8ef4ed5b49126bfdf1768 # {"$openapi":"base"}
images:
- name: jasonblanchard/di-notebook
  newTag: "b69a069fc18c2a8a80c8ef4ed5b49126bfdf1768" # {"$openapi":"version"}
commonAnnotations:
  version: "b69a069fc18c2a8a80c8ef4ed5b49126bfdf1768" # {"$openapi":"version"}
