apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
- https://github.com/jasonblanchard/di-notebook/deploy/k8s/production?ref=e64b985983cd5bd08ddcc32557a9db453762ed9c # {"$openapi":"base"}
images:
- name: jasonblanchard/di-notebook
  newTag: "e64b985983cd5bd08ddcc32557a9db453762ed9c" # {"$openapi":"version"}
commonAnnotations:
  version: "e64b985983cd5bd08ddcc32557a9db453762ed9c" # {"$openapi":"version"}
