apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
- https://github.com/jasonblanchard/di-notebook/deploy/k8s/production?ref=d4c6c16e2d8bdd84f640bac29eca07782cb96bc6 # {"$openapi":"base"}
images:
- name: jasonblanchard/di-notebook
  newTag: "d4c6c16e2d8bdd84f640bac29eca07782cb96bc6" # {"$openapi":"version"}
commonAnnotations:
  version: "d4c6c16e2d8bdd84f640bac29eca07782cb96bc6" # {"$openapi":"version"}
