apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
- https://github.com/jasonblanchard/di-notebook/deploy/k8s/production?ref=fffeb0c7bc45cf35f1911d747449901b32c0e2a9 # {"$openapi":"base"}
images:
- name: jasonblanchard/di-notebook
  newTag: "fffeb0c7bc45cf35f1911d747449901b32c0e2a9" # {"$openapi":"version"}
commonAnnotations:
  version: "fffeb0c7bc45cf35f1911d747449901b32c0e2a9" # {"$openapi":"version"}
