apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
- https://github.com/jasonblanchard/di-notebook/deploy/k8s/production?ref=d40125c6d37dd71fab2b464637e26b07f5e7ceab # {"$openapi":"base"}
images:
- name: jasonblanchard/di-notebook
  newTag: "d40125c6d37dd71fab2b464637e26b07f5e7ceab" # {"$openapi":"version"}
commonAnnotations:
  version: "d40125c6d37dd71fab2b464637e26b07f5e7ceab" # {"$openapi":"version"}
