apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
- https://github.com/jasonblanchard/di-notebook/deploy/k8s/production?ref=129cb8f23363a90912677801e8c83dda2030a3bd # {"$openapi":"base"}
images:
- name: jasonblanchard/di-notebook
  newTag: "129cb8f23363a90912677801e8c83dda2030a3bd" # {"$openapi":"version"}
commonAnnotations:
  version: "129cb8f23363a90912677801e8c83dda2030a3bd" # {"$openapi":"version"}
