apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
- https://github.com/jasonblanchard/di-entry/deploy/k8s/production?ref=4cda5892a970f8b531f096090956642894b93e17 # {"$openapi":"base"}
images:
- name: jasonblanchard/di-notebook
  newTag: "4cda5892a970f8b531f096090956642894b93e17" # {"$openapi":"version"}
commonAnnotations:
  version: "4cda5892a970f8b531f096090956642894b93e17" # {"$openapi":"version"}
