apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
  - https://github.com/jasonblanchard/di-notebook/deploy/k8s/production?ref=ba892ff7c8bc4ad2ef651377c8ff8c3078161d16 # {"$openapi":"base"}
images:
  - name: jasonblanchard/di-notebook
    newTag: "ba892ff7c8bc4ad2ef651377c8ff8c3078161d16" # {"$openapi":"version"}
commonAnnotations:
  version: "ba892ff7c8bc4ad2ef651377c8ff8c3078161d16" # {"$openapi":"version"}
