apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di
bases:
- https://github.com/jasonblanchard/di-velocity/deploy/k8s/production?ref=ba51e1df39df72e3266547473099b4962c165a6b # {"$openapi":"base"}
images:
- name: jasonblanchard/di-velocity
  newTag: "ba51e1df39df72e3266547473099b4962c165a6b" # {"$openapi":"version"}
commonAnnotations:
  version: "ba51e1df39df72e3266547473099b4962c165a6b" # {"$openapi":"version"}
