apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: public-web
spec:
  project: default
  source:
    repoURL: https://github.com/jasonblanchard/di-public-web
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}
