apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di
bases:
- https://github.com/jasonblanchard/di-entry/deploy/k8s/production?ref=6ce95785a42fffef0e094f4cf782a711417de8e1 # {"$openapi":"base"}
images:
- name: jasonblanchard/di-entry
  newTag: "6ce95785a42fffef0e094f4cf782a711417de8e1" # {"$openapi":"version"}
commonAnnotations:
  version: "6ce95785a42fffef0e094f4cf782a711417de8e1" # {"$openapi":"version"}
