apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
- https://github.com/jasonblanchard/di-gql-edge/deploy/k8s/production?ref=913342c7374449717de6e110b0881c1046cf9da6 # {"$openapi":"base"}
images:
- name: jasonblanchard/di-gql-edge
  newTag: "913342c7374449717de6e110b0881c1046cf9da6" # {"$openapi":"version"}
commonAnnotations:
  version: "913342c7374449717de6e110b0881c1046cf9da6" # {"$openapi":"version"}
