apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
- https://github.com/jasonblanchard/di-gql-edge/deploy/k8s/production?ref=85fd5420ac6c86846375666ae54085e3fb3d0c78 # {"$openapi":"base"}
images:
- name: jasonblanchard/di-gql-edge
  newTag: "85fd5420ac6c86846375666ae54085e3fb3d0c78" # {"$openapi":"version"}
commonAnnotations:
  version: "85fd5420ac6c86846375666ae54085e3fb3d0c78" # {"$openapi":"version"}
