apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
- https://github.com/jasonblanchard/di-authn/deploy/k8s/production?ref=5015e93d351c4d7d13939845eac10676798330b8 # {"$openapi":"base"}
images:
- name: jasonblanchard/di-authn
  newTag: "5015e93d351c4d7d13939845eac10676798330b8" # {"$openapi":"version"}
commonAnnotations:
  version: "5015e93d351c4d7d13939845eac10676798330b8" # {"$openapi":"version"}
