apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
- https://github.com/jasonblanchard/di-authn/deploy/k8s/production?ref=58bf5d54c14fb23329f36dcaa20f1fd30ee40b5c # {"$openapi":"base"}
images:
- name: jasonblanchard/di-authn
  newTag: "58bf5d54c14fb23329f36dcaa20f1fd30ee40b5c" # {"$openapi":"version"}
commonAnnotations:
  version: "58bf5d54c14fb23329f36dcaa20f1fd30ee40b5c" # {"$openapi":"version"}
