apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
- https://github.com/jasonblanchard/di-authn/deploy/k8s/production?ref=49f2e9fa4f4a17b6d9ca10f24b17aec6b3cbf02d # {"$openapi":"base"}
images:
- name: jasonblanchard/di-authn
  newTag: "49f2e9fa4f4a17b6d9ca10f24b17aec6b3cbf02d" # {"$openapi":"version"}
commonAnnotations:
  version: "49f2e9fa4f4a17b6d9ca10f24b17aec6b3cbf02d" # {"$openapi":"version"}
