apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
- https://github.com/jasonblanchard/di-authn/deploy/k8s/production?ref=0381c7a9a1f6bc05103cc05754eb3a7f3cc35579 # {"$openapi":"base"}
images:
- name: jasonblanchard/di-authn
  newTag: "0381c7a9a1f6bc05103cc05754eb3a7f3cc35579" # {"$openapi":"version"}
commonAnnotations:
  version: "0381c7a9a1f6bc05103cc05754eb3a7f3cc35579" # {"$openapi":"version"}
