apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
- https://github.com/jasonblanchard/di-authn/deploy/k8s/production?ref=f8969b332ca851eecb03dfb7ae36ab37a92bcf0b # {"$openapi":"base"}
images:
- name: jasonblanchard/di-authn
  newTag: "f8969b332ca851eecb03dfb7ae36ab37a92bcf0b" # {"$openapi":"version"}
commonAnnotations:
  version: "f8969b332ca851eecb03dfb7ae36ab37a92bcf0b" # {"$openapi":"version"}
