apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
- https://github.com/jasonblanchard/di-authn/deploy/k8s/production?ref=25f0b47300fb06143d9b44e8a975c5d5d588fa5b # {"$openapi":"base"}
images:
- name: jasonblanchard/di-authn
  newTag: "25f0b47300fb06143d9b44e8a975c5d5d588fa5b" # {"$openapi":"version"}
commonAnnotations:
  version: "25f0b47300fb06143d9b44e8a975c5d5d588fa5b" # {"$openapi":"version"}
