name: Dispatch deploy
on:
  repository_dispatch:
    types: [deploy]
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy commit
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/deploy-commit
      with:
        service: ${{ github.event.client_payload.service }}
        environment: ${{ github.event.client_payload.environment }}
        version: ${{ github.event.client_payload.version }}
