name: Manual deploy
on:
  workflow_dispatch:
    inputs:
      service:
        description: 'Name of service to deploy'
        required: true
        default: ''
      environment:
        description: 'Environment to deploy to'
        required: true
      version:
        description: 'Version to deploy (git SHA)'
        required: true

jobs:
  manual-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Manual deploy
        run: |
          curl -XPOST -u "${{ secrets.DEPLOY_USERNAME}}:${{secrets.DEPLOY_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/jasonblanchard/di-deploy/dispatches --data '{"event_type": "deploy", "client_payload": { "version": "${{ github.event.inputs.version }}", "service": "${{ github.event.inputs.service }}", "environment": "${{ github.event.inputs.environment }}"} }'
