name: Manual deploy
on:
  workflow_dispatch:
    inputs:
      service:
        description: 'Name of service to deploy'
        required: true
        default: ''
      environment:
        description: 'Environment to deploy to'
        required: true
      version:
        description: 'Version to deploy (git SHA)'
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
    - uses: actions/checkout@v2
    - uses: actions/deploy
      with:
        service: github.event.inputs.service
        environment: github.event.inputs.environment
        version: github.event.inputs.version
