apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
- https://github.com/jasonblanchard/di-workspace-web/deploy/k8s/production?ref=bf1a526b1d73a8e865f2d4defeba5ea20a492dca # {"$openapi":"base"}
images:
- name: jasonblanchard/di-workspace-web
  newTag: "bf1a526b1d73a8e865f2d4defeba5ea20a492dca" # {"$openapi":"version"}
commonAnnotations:
  version: "bf1a526b1d73a8e865f2d4defeba5ea20a492dca" # {"$openapi":"version"}
