apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
- https://github.com/jasonblanchard/di-workspace-web/deploy/k8s/production?ref=607167bd465997798daea2b8bc3f16635291ac8e # {"$openapi":"base"}
images:
- name: jasonblanchard/di-workspace-web
  newTag: "607167bd465997798daea2b8bc3f16635291ac8e" # {"$openapi":"version"}
commonAnnotations:
  version: "607167bd465997798daea2b8bc3f16635291ac8e" # {"$openapi":"version"}
