apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
  - https://github.com/jasonblanchard/di-workspace-web/deploy/k8s/production?ref=d36b448cedf1c980a08433ce91c98e7f1ffd37d1 # {"$openapi":"base"}
images:
  - name: jasonblanchard/di-workspace-web
    newTag: "d36b448cedf1c980a08433ce91c98e7f1ffd37d1" # {"$openapi":"version"}
commonAnnotations:
  version: "d36b448cedf1c980a08433ce91c98e7f1ffd37d1" # {"$openapi":"version"}
