apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
- https://github.com/jasonblanchard/di-workspace-web/deploy/k8s/production?ref=0873e31f754d39f0a2708df47019aedf23b401e2 # {"$openapi":"base"}
images:
- name: jasonblanchard/di-workspace-web
  newTag: "0873e31f754d39f0a2708df47019aedf23b401e2" # {"$openapi":"version"}
commonAnnotations:
  version: "0873e31f754d39f0a2708df47019aedf23b401e2" # {"$openapi":"version"}
