apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
  - https://github.com/jasonblanchard/di-workspace-web/deploy/k8s/production?ref=f2b0848742b6c4b0696158079dc3e50e27f7215e # {"$openapi":"base"}
images:
  - name: jasonblanchard/di-workspace-web
    newTag: "f2b0848742b6c4b0696158079dc3e50e27f7215e" # {"$openapi":"version"}
commonAnnotations:
  version: "f2b0848742b6c4b0696158079dc3e50e27f7215e" # {"$openapi":"version"}
