apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
  - https://github.com/jasonblanchard/di-workspace-web/deploy/k8s/production?ref=4b2dfe373a02827d26a346fa813588a6acf488af # {"$openapi":"base"}
images:
  - name: jasonblanchard/di-workspace-web
    newTag: "4b2dfe373a02827d26a346fa813588a6acf488af" # {"$openapi":"version"}
commonAnnotations:
  version: "4b2dfe373a02827d26a346fa813588a6acf488af" # {"$openapi":"version"}
