apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
- https://github.com/jasonblanchard/di-workspace-web/deploy/k8s/production?ref=78813e0d0a91bf5edfc070ed4effdb6d8d09c3aa # {"$openapi":"base"}
images:
- name: jasonblanchard/di-workspace-web
  newTag: "78813e0d0a91bf5edfc070ed4effdb6d8d09c3aa" # {"$openapi":"version"}
commonAnnotations:
  version: "78813e0d0a91bf5edfc070ed4effdb6d8d09c3aa" # {"$openapi":"version"}
