apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di-production
bases:
- https://github.com/jasonblanchard/di-workspace-web/deploy/k8s/production?ref=3b4dbd4a28de6c60e7f367710e363672a1e3abc7 # {"$openapi":"base"}
images:
- name: jasonblanchard/di-workspace-web
  newTag: "3b4dbd4a28de6c60e7f367710e363672a1e3abc7" # {"$openapi":"version"}
commonAnnotations:
  version: "3b4dbd4a28de6c60e7f367710e363672a1e3abc7" # {"$openapi":"version"}
