apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di
bases:
- https://github.com/jasonblanchard/di-workspace-web/deploy/k8s/production?ref=63d90e5ba723c687841ac8de5e540ea59cbfb8f6 # {"$openapi":"base"}
images:
- name: jasonblanchard/di-workspace-web
  newTag: "63d90e5ba723c687841ac8de5e540ea59cbfb8f6" # {"$openapi":"version"}
commonAnnotations:
  version: "63d90e5ba723c687841ac8de5e540ea59cbfb8f6" # {"$openapi":"version"}
